#ifndef CONSTANTS_H
#define CONSTANTS_H

#define VERSION "0.1.0"

#define SENSOR_PIN1 4
#define SENSOR_PIN2 5

#define ACTUATOR_PIN 15

#define SSID "CLARO_WIFI09"
#define SSID_PASSWORD "Marcecata123"

#define MQTT_BROKER "broker.hivemq.com"
#define MQTT_CLIENT_ID "ESP_COUNTER"
#define CAPACITY 10
#define MQTT_IN_TOPIC "EAFIT_PARKING/INPUT"
#define MQTT_OUT_TOPIC "EAFIT_PARKING/OUTPUT"
#define MQTT_REGISTER_INPUT_TOPIC "EAFIT_PARKING/REGISTER/INPUT"
#define MQTT_REGISTER_OUTPUT_TOPIC "EAFIT_PARKING/REGISTER/OUTPUT"

#define LIGHTS_PIN 2
#define LIGHTS_COUNT 8

#define SENSOR_KEY 0xAA

#endif
